# Generated by Django 5.1.4 on 2025-01-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('task', models.CharField(max_length=200)),
                ('priority', models.IntegerField()),
                ('detail', models.TextField()),
            ],
        ),
    ]
